language: python
python:
    - "3.5"
    - "3.6"

env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=master

install:
- pip install -r requirements.txt
script:
- coverage run manage.py test
after_success:
- coverage report